const HttpResponseMessage = {
  ERROR: {
    USER_BLOCKED_OR_NOT_EXIST:
      "User does not exist or blocked. Please sign up.",
    USER_BLOCKED: "User is blocked.",
    INCORRECT_USERNAME_OR_PASSWORD: "Incorrect username or password.",
    ADDRESS_NOT_FOUND: "Address not found",
    PRODUCT_NOT_FOUND_ON_CART: "Product not found in the cart",
    CART_NOT_FOUND: "Cart not found",
    PASSWORD_INCORRECT: "Incorrect current password",
    TOKEN_EXPIRED: "Invalid or expired token",
    EMAIL_NOT_FOUND: "The email is not found",
    SERVER_ERROR: "The server error",
    OTP_RESEND: "Failed to resend OTP. Please try again.",
    INVALID_OTP: "Invalid OTP",
    OTP_EXPIRED: "OTP has expired.",
    USER_STATUS_UPDATE: "Error updating the user status",
    USER_NOT_FOUND: "The user is not found",
    USERS_NOT_FOUND: "the users are not found...",
    USERS_STATUSES: "Error get all user status",
    REPORT_GENERATE: "Error generating report",
    USER_EXIST: "User already exists.",
    PRODUCT_STATUS_UPDATE: "Error updating product status",
    PRODUCT_FETCH: "Error fetching the product",
    PRODUCT_UPDATE: "Error updating the product",
    PRODUCT_CREATION: "Error creating the product",
    PRODUCT_NOT_FOUND: "The product is not found",
    PRODUCT_EXIST: "The product already exists",
    ORDER_RETURN_COMPLETED: "Invalid or already completed return",
    ORDER_NOT_FOUND: "The order is not found",
    OFFER_ID: "Invalid offer ID",
    NO_COUPON_APPLIED: "No coupon applied to the cart.",
    OFFER_TYPE: "Invalid applicable offer type",
    OFFER_NOT_FOUND: "The offer is not found",
    OFFER_EXIST: "The offer already exists",
    COUPON_NOT_FOUND: "The coupon is not found",
    COUPON_EXPIRED: "Coupon has expired.",
    COUPON_EXIST: "The coupon already exists",
    COUPON_CREATION: "Server error occurred while creating the coupon",
    CATEGORY_FETCH: "Error fetching categories",
    CATEGORY_NOT_FOUND: "The category is not found!",
    CATEGORY_CREATION: "Error creating the category",
    CATEGORY_EXIST: "The category is already exists",
    CATEGORY_UPDATE: "Error updating category",
    CATEGORY_STATUS_UPDATE: "Error updating category status",
    BANNER_CREATION: "Error creating the banner",
    BANNER_EXIST: "The banner is already exist!",
    BANNER_NOT_FOUND: "The banner is not found!",
    BANNER_UPDATE: "Error updating banner",
  },
  SUCCESS: {
    PRODUCT_DELETED_FROM_CART: "The product is deleted from the cart",
    PRODUCT_ADDED_TO_CART: "Product added to cart!",
    PRODUCT_QUANTITY_UPDATE: "Quantity updated successfully",
    PASSWORD_UPDATE: "Password updated successfully",
    PASSWORD_CORRECT: "Password is correct",
    EMAIL_SENT: "The mail is sent successfully",
    OTP_RESEND: "OTP resend successfully",
    USER_VERIFY: "the user verified successful",
    USER_SIGNUP: "User signup successful",
    USER_LOGIN: "User login successfully",
    USER_STATUS_UPDATE: "User status updated successfully",
    PRODUCT_STATUS_UPDATE: "product status updated successfully",
    PRODUCT_UPDATE: "Product updated successfully",
    PRODUCT_CREATION: "Product created successfully",
    ORDER_RETURN_APPROVED: "Return approved and amount credited to wallet",
    ORDER_RETURN_REQUEST: "The return request is handled successfully",
    ORDER_FETCH: "The order is fetched successfully",
    OFFER_UPDATE:
      "The offer is updated successfully and associated with products",
    OFFER_CREATION:
      "The offer is created successfully and added to the products",
    COUPON_APPLIED: "Coupon applied successfully!",
    COUPON_UPDATE: "coupon updated successfully",
    COUPON_CREATION: "Coupon created successfully",
    BANNER_CREATION: "banner created successfully",
    BANNER_UPDATE: "Banner updated successfully",
    CATEGORY_UPDATE: "Category updated successfully",
    CATEGORY_STATUS_UPDATE: "category status updated successfully",
    CATEGORY_CREATION: "category created successfully",
  },
};

module.exports = HttpResponseMessage;
