services:
  nginx:
    container_name: mt-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    env_file:
      - ./.env
    working_dir: /app
    volumes:
      - .:/app
    command: npm run start
